// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeCJo8DDvy26QQPlbaeZX_oOCoNpZbENw',
    appId: '1:409137397922:web:cd30d295dc35224c3ad7fb',
    messagingSenderId: '409137397922',
    projectId: 'fire-65b90',
    authDomain: 'fire-65b90.firebaseapp.com',
    storageBucket: 'fire-65b90.appspot.com',
    measurementId: 'G-LZJ4TEMW0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKvLGKg8fSVUcHofpTNr2TKCe9_mMqAvA',
    appId: '1:409137397922:android:6c8636f2323426de3ad7fb',
    messagingSenderId: '409137397922',
    projectId: 'fire-65b90',
    storageBucket: 'fire-65b90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC3ieZKtePWchA9kWBGrL9_LuK4QqVIyY',
    appId: '1:409137397922:ios:45a8e47a946cc2ea3ad7fb',
    messagingSenderId: '409137397922',
    projectId: 'fire-65b90',
    storageBucket: 'fire-65b90.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC3ieZKtePWchA9kWBGrL9_LuK4QqVIyY',
    appId: '1:409137397922:ios:caeebd452ff847aa3ad7fb',
    messagingSenderId: '409137397922',
    projectId: 'fire-65b90',
    storageBucket: 'fire-65b90.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
